### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by bouncing-seal** [pomirs-workers/cam-play#1]
Идея проста и гениальна:
В ограниченную зону, за которой ведут наблюдение две камеры, влетает воланчик (в перспективе - что угодно). Камеры снимают траекторию полёта предмета, работая с которой высчитывается координата падения предмета (в пределах ограниченной зоны). Данная информация идёт роботу-ведру, который едет в указанную точку и ловит предмет на подлёте.

**Comment by yungvldai** [comment]
))))
